export const SneakersArray = [
    { stoq: 10, sale: 100, img: require('../../assets/tenis-1.png'), id: 1, name: "Nike Air Max", price: 199.99, favorite: false, category: "stoq" },
    { stoq: 20, sale: 90, img: require('../../assets/tenis-2.png'), id: 2, name: "Adidas Ultraboost", price: 179.99, favorite: true, category: "stoq" },
    { stoq: 30, sale: 80, img: require('../../assets/tenis-3.png'), id: 3, name: "Puma RS-X", price: 149.99, favorite: false, category: "stoq" },
    { stoq: 40, sale: 70, img: require('../../assets/tenis-4.png'), id: 4, name: "New Balance 574", price: 129.99, favorite: false, category: "new arrival" },
    { stoq: 50, sale: 60, img: require('../../assets/tenis-5.png'), id: 5, name: "Reebok Classic Leather", price: 99.99, favorite: true, category: "stoq" },
    { stoq: 60, sale: 50, img: require('../../assets/tenis-6.png'), id: 6, name: "Vans Old Skool", price: 79.99, favorite: false, category: "new arrival" },
    { stoq: 70, sale: 40, img: require('../../assets/tenis-7.png'), id: 7, name: "Converse Chuck Taylor All Star", price: 69.99, favorite: false, category: "stoq" },
    { stoq: 80, sale: 30, img: require('../../assets/tenis-8.png'), id: 8, name: "Asics Gel-Lyte III", price: 119.99, favorite: false, category: "stoq" },
    { stoq: 90, sale: 20, img: require('../../assets/tenis-9.png'), id: 9, name: "Under Armour HOVR Phantom", price: 159.99, favorite: false, category: "new arrival" },
    { stoq: 100, sale: 10, img: require('../../assets/tenis-10.png'), id: 10, name: "Skechers D'Lites", price: 89.99, favorite: false, category: "stoq" },
    { stoq: 110, sale: 110, img: require('../../assets/tenis-11.png'), id: 11, name: "Salomon Speedcross", price: 169.99, favorite: true, category: "stoq" },
    { stoq: 120, sale: 120, img: require('../../assets/tenis-12.png'), id: 12, name: "Mizuno Wave Rider", price: 139.99, favorite: false, category: "new arrival" },
    { stoq: 130, sale: 130, img: require('../../assets/tenis-13.png'), id: 13, name: "Brooks Ghost", price: 129.99, favorite: false, category: "stoq" },
    { stoq: 140, sale: 140, img: require('../../assets/tenis-14.png'), id: 14, name: "Hoka One One Clifton", price: 149.99, favorite: false, category: "stoq" },
    { stoq: 50, sale: 30, img: require('../../assets/tenis-15.png'), id: 15, name: "Merrell Trail Glove", price: 109.99, favorite: false, category: "new arrival" },
    { stoq: 60, sale: 20, img: require('../../assets/tenis-16.png'), id: 16, name: "Fila Disruptor II", price: 99.99, favorite: true, category: "stoq" },
    { stoq: 70, sale: 10, img: require('../../assets/tenis-17.png'), id: 17, name: "Lacoste Carnaby", price: 119.99, favorite: false, category: "stoq" },
    { stoq: 80, sale: 90, img: require('../../assets/tenis-18.png'), id: 18, name: "Timberland 6-Inch Premium", price: 179.99, favorite: true, category: "new arrival" },
    { stoq: 90, sale: 80, img: require('../../assets/tenis-19.png'), id: 19, name: "DC Shoes Court Graffik", price: 89.99, favorite: false, category: "stoq" },
    { stoq: 100, sale: 70, img: require('../../assets/tenis-20.png'), id: 20, name: "Palladium Pampa", price: 79.99, favorite: false, category: "stoq" },
    { stoq: 110, sale: 60, img: require('../../assets/tenis-21.png'), id: 21, name: "Reebok Nano X", price: 129.99, favorite: false, category: "new arrival" },
    { stoq: 120, sale: 50, img: require('../../assets/tenis-22.png'), id: 22, name: "Vans Sk8-Hi", price: 89.99, favorite: true, category: "stoq" },
    { stoq: 130, sale: 40, img: require('../../assets/tenis-23.png'), id: 23, name: "Adidas Stan Smith", price: 99.99, favorite: false, category: "stoq" },
    { stoq: 140, sale: 30, img: require('../../assets/tenis-24.png'), id: 24, name: "New Balance 990v5", price: 169.99, favorite: false, category: "new arrival" }
];
